# This workflow will build, test and deploy a .NET 8.0 Web API application
# for the Dental Reservation system.

name: .NET Web API Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: ../CabinetDentaire.sln
      Project_Path: api/api.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    # Build the application
    - name: Build
      run: dotnet build $env:Solution_Name --no-restore --configuration ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test $env:Solution_Name --no-build --verbosity normal --configuration ${{ matrix.configuration }}

    # Publish the application
    - name: Publish
      run: dotnet publish $env:Project_Path --no-build --configuration ${{ matrix.configuration }} --output ./publish

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dental-api-${{ matrix.configuration }}
        path: ./publish
